= Becoming an S1 Trip Leader

Being an S1 Trip Leader allows you to lead trips into the backcountry with little to no snow travel (e.g., the High Sierra in the summer).
The objectives don't need to be 5th class but 3rd class is a good minimum.

While the SCMA refers to this initial trip as an evaluation I see it more as a formality.
If you have any questions, do not hesitate to ask.
You will not be dinged for questions.

== High Priority Tasks

The two highest-priority tasks to complete are:

* Schedule your Wilderness First Aid course
* Book permits

== Wilderness First Aid

There are several options for WFA but I recommend the courses offered by NOLS.
They have the most offerings.
See the NOLS WFA page for course availability.
Aim to complete the WFA at least a month before the trip.

The SCMA will reimburse the full cost of your initial WFA course after your first S1 trip.

== Permits

Permit booking season starts in December.
Sierra permits become available on a 6 month rolling window starting at 7am Pacific.
I.e. Tomorrow at 7am, permits for the day 6 months from now will become available.

I find that 4-day trips are a pretty good sweet spot.
This gives 1 day to hike in, 2 for objectives, and 1 to hike out.
I usually shoot for a Thursday entry and a Sunday exit.

For S1 trips, the trip leader (you) needs to book the permits.
Try to get enough permits for 4-8 people depending on the area and available objectives.
Unlike G trips, participants must obtain approval from both trip leaders to attend an S1 trip.

The Sierra does see the occasional summer storm.
I've learned it is sometimes better to cancel or postpone a trip in response to a bad forecast than to charge ahead.
To mitigate bad weather consider booking another set of permits for two weeks later.
If the first date works out, you can cancel the second or use them for another trip.

Coordinate objectives and dates with your co-leader.

The SCMA will reimburse any permit/camp fees after the trip.

== Additional Tasks

After you have the WFA and permits figured out, read the How to Become a Trip Leader section in the SCMA Member Handbook and follow the directions there.
Notify the SCMA Safety Chair that you are interested in becoming an S1 trip leader.

== Perks

Besides the pleasure of sharing the magic of the High Sierra with others, being a trip leader comes with some perks including:

* Gear discounts
* Raffles for leader days
